import './deterministic-check.mjs'
import '../tests/unit/teamConfig.test.mjs'
import '../tests/unit/playerTimers.test.mjs'
import '../tests/unit/movement.test.mjs'
import '../tests/unit/decision.test.mjs'
import '../tests/unit/teamSetup.test.mjs'
import '../tests/unit/pinRules.test.mjs'
